baseURL = "https://diyruz.github.io/catalog/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
  commentoEnable = true
   site_logo = "img/zigbee.jpg"